TILE_SIZE = 30
ROWS = 16
COLS = 24
START_ROW = 8
MAP_WIDTH = COLS * TILE_SIZE
MAP_HEIGHT = ROWS * TILE_SIZE
MARGIN = 20
STAT_WIDTH = COLS * TILE_SIZE
STAT_HEIGHT = 5 * TILE_SIZE
WINDOW_WIDTH = MAP_WIDTH + MARGIN * 2
WINDOW_HEIGHT = MAP_HEIGHT + STAT_HEIGHT + MARGIN * 3
RANKING_PATH = './data/ranking.json'
SAVEGAME_PATH = './data/savegame.pkl'
BGM_MENU_PATH = './assets/sounds/HappyPlace.mp3' # Track - Alexander Nakarada - Happy Place
BGM_GAME_PATH = './assets/sounds/gentleman.mp3'